[package]
name = "ramen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
atty = "0.2.14"
clap = { version = "4.5.21", features = ["derive", "string"] }
once_cell = "1.20.2"
regex = "1.11.1"
thiserror = "2.0.3"
yaml-rust = "0.4.5"
